# Generated by Django 3.2.7 on 2022-01-03 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EventModel',
            fields=[
                ('eventId', models.AutoField(primary_key=True, serialize=False)),
                ('eventName', models.CharField(max_length=100)),
                ('eventDesc', models.CharField(max_length=1000)),
                ('eventCoOrdinator1', models.CharField(max_length=50)),
                ('eventCoOrdinator1Mob', models.CharField(max_length=15)),
                ('eventCoOrdinator2', models.CharField(blank=True, max_length=50)),
                ('eventCoOrdinator2Mob', models.CharField(blank=True, max_length=15)),
                ('poster', models.ImageField(upload_to='media')),
            ],
        ),
        migrations.CreateModel(
            name='RegistrationModel',
            fields=[
                ('playerId', models.AutoField(primary_key=True, serialize=False)),
                ('fullName', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('collegeName', models.CharField(max_length=100)),
                ('mobNo', models.CharField(max_length=15)),
                ('event', models.CharField(max_length=50)),
                ('datetimestamp', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
