# Generated by Django 3.2.4 on 2021-09-17 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RegistrationModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullName', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('collegeName', models.CharField(max_length=100)),
                ('mobNo', models.CharField(max_length=15)),
                ('event', models.CharField(max_length=50)),
                ('datetimestamp', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
