# Generated by Django 3.0.5 on 2021-12-31 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventModel',
            fields=[
                ('eventId', models.AutoField(primary_key=True, serialize=False)),
                ('eventName', models.CharField(max_length=100)),
                ('eventDesc', models.CharField(max_length=1000)),
                ('eventCoOrdinator1', models.CharField(max_length=50)),
                ('eventCoOrdinator1Mob', models.CharField(max_length=15)),
                ('eventCoOrdinator2', models.CharField(max_length=50)),
                ('eventCoOrdinator2Mob', models.CharField(max_length=15)),
                ('poster', models.ImageField(upload_to='media')),
            ],
        ),
        migrations.RemoveField(
            model_name='registrationmodel',
            name='id',
        ),
        migrations.AddField(
            model_name='registrationmodel',
            name='playerId',
            field=models.AutoField(default=-1, primary_key=True, serialize=False),
        ),
    ]
