# Generated by Django 3.0.5 on 2022-01-04 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrationmodel',
            name='secondPlayerMobNo',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AddField(
            model_name='registrationmodel',
            name='secondPlayerName',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
