# Generated by Django 3.0.5 on 2021-12-31 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20211231_1950'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrationmodel',
            name='playerId',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
