# Generated by Django 3.2.7 on 2021-12-31 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20211231_1741'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrationmodel',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
