# Generated by Django 4.0.1 on 2022-01-27 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20220104_1052'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageModel',
            fields=[
                ('imageId', models.AutoField(primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='images')),
                ('imageClass', models.CharField(choices=[('SPoorthi', 'SPoorthi 2022'), ('Agility', 'Agility 2021'), ('Glimpse', 'Glimpse of Past Years')], max_length=10)),
            ],
        ),
    ]
